gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showCommandLog: false
  scrollHeight: 4
  sidePanelWidth: 0.3
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers
  parseEmoji: true
