"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1000

format = """
[](fg:#7aa2f7)\
$os\
$directory\
[](fg:#7aa2f7 bg:#3b4261)\
$git_branch\
$git_status\
[](fg:#3b4261 bg:#1f2335)\
$nodejs\
$rust\
$golang\
$python\
[ ](fg:#1f2335)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#7aa2f7 fg:#1a1b26"
format = '[ $symbol ]($style)'

[os.symbols]
Macos = ""

[directory]
style = "bg:#7aa2f7 fg:#1a1b26 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/code" = " code"

[git_branch]
symbol = ""
style = "bg:#3b4261 fg:#7aa2f7"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3b4261 fg:#e0af68"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#1f2335 fg:#9ece6a"
format = '[ $symbol $version ]($style)'

[rust]
symbol = ""
style = "bg:#1f2335 fg:#f7768e"
format = '[ $symbol $version ]($style)'

[golang]
symbol = ""
style = "bg:#1f2335 fg:#7dcfff"
format = '[ $symbol $version ]($style)'

[python]
symbol = ""
style = "bg:#1f2335 fg:#7dcfff"
format = '[ $symbol $version ]($style)'

[cmd_duration]
min_time = 500
style = "fg:#e0af68"
format = '[  $duration ]($style)'

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #9ece6a)"
